; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[views_bulk_operations][version] = "3.2"

projects[auto_nodetitle][version] = "1.0"

projects[ctools][version] = "1.4"

projects[chosen][version] = "2.0-beta4"

projects[ckeditor][version] = "1.15"

projects[colectomy][version] = "1.0-beta2"

projects[content_access][version] = "1.2-beta2"

projects[context_admin][version] = "1.2"

projects[countries][version] = "2.1"

projects[crumbs][version] = "2.0-beta19"

projects[facetapi][version] = "1.5"

projects[custom_search][version] = "1.16"

projects[date][version] = "2.8"

projects[ds][version] = "2.6"

projects[eck][version] = "2.0-rc4"

projects[ember_support][version] = "1.0-alpha2"

projects[entity][version] = "1.5"

projects[entityreference][version] = "1.1"

projects[facetapi_pretty_paths][version] = "1.1"

projects[facetapi_tagcloud][version] = "1.0-beta1"

projects[field_collection][version] = "1.0-beta7"

projects[field_group][version] = "1.4"

projects[google_analytics][version] = "2.0"

projects[panels][version] = "3.4"

projects[inline_entity_form][version] = "1.5"

projects[insert][version] = "1.3"

projects[jquery_update][version] = "2.4"

projects[libraries][version] = "2.2"

projects[link][version] = "1.2"

projects[metatag][version] = "1.0-rc2"

projects[module_filter][version] = "1.8"

projects[navbar][version] = "1.4"

projects[pathauto][version] = "1.2"

projects[print][version] = "2.0"

projects[r4032login][version] = "1.7"

projects[range][version] = "1.1"

projects[readmorecontrol][version] = "1.2"

projects[save_draft][version] = "1.4"

projects[search_api][version] = "1.13"

projects[search_api_ajax][version] = "1.2"

projects[search_api_autocomplete][version] = "1.1"

projects[search_api_db][version] = "1.3"

projects[search_api_taxonomy][version] = "1.x-dev"

projects[search_facetapi][version] = "1.0-beta2"

projects[select_with_style][version] = "1.14"

projects[seo_ui][version] = "1.0"

projects[sliderfield][version] = "2.1-beta1"

projects[social-share][version] = "2.1"

projects[tagclouds][version] = "1.10"

projects[taxonomy_facets][version] = "1.5"

projects[taxonomy_manager][version] = "1.0"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.2"

projects[unique_field][version] = "1.0-rc1"

projects[views][version] = "3.8"

projects[views_infinite_scroll][version] = "1.1"

projects[views_tree][version] = "2.0"

projects[webform][version] = "4.0-rc5"

projects[xmlsitemap][version] = "2.0"

; Themes
projects[bootstrap][version] = "3.0"

projects[bootstrap-business][version] = "1.0"

projects[ember][version] = "2.0-alpha2+28-dev"

projects[rubik][version] = "4.0"

projects[tao][version] = "3.1"

; Modules
projects[conditional_fields][type] = "module"
projects[conditional_fields][download][type] = "git"
projects[conditional_fields][download][url] = "http://git.drupal.org/project/conditional_fields.git"
projects[conditional_fields][download][branch] = "7.x-3.x"
projects[conditional_fields][download][revision] = "78ecb040828f8b9b38ca6e1c37a69782da8d9f86"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[bootstrapdb][download][type] = ""
projects[bootstrapdb][download][url] = ""
projects[bootstrapdb][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[chosen][download][type] = ""
libraries[chosen][download][url] = ""
libraries[chosen][directory_name] = "chosen"
libraries[chosen][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

